import 'dart:math';

abstract final class PulseGreetings {
  static String? _last;

  /// Short, natural greetings. Avoids repeating the last one.
  static String forUser(String rawName) {
    final name = rawName.trim();
    final hour = DateTime.now().hour;
    final pool = name.isEmpty
        ? _anonymous(hour)
        : _named(hour, _firstName(name));

    if (pool.length == 1) {
      _last = pool.first;
      return pool.first;
    }

    String next;
    do {
      next = pool[Random().nextInt(pool.length)];
    } while (next == _last && pool.length > 1);
    _last = next;
    return next;
  }

  static String _firstName(String name) {
    final parts = name.split(RegExp(r'\s+'));
    final first = parts.first;
    if (first.isEmpty) return name;
    return first[0].toUpperCase() + first.substring(1);
  }

  static List<String> _named(int hour, String name) {
    if (hour < 5) {
      return [
        'Still awake, $name?',
        'Late night check-in, $name',
        'Take it easy, $name',
        'Quiet hours suit you, $name',
        'Glad you’re here, $name',
        'No rush tonight, $name',
        'One gentle step, $name',
        'Rest when you can, $name',
        'You’ve done enough, $name',
        'Soft night ahead, $name',
        'Keep it light, $name',
        'Breathe — you’re okay, $name',
        'Almost morning, $name',
        'Be kind to yourself, $name',
        'Small progress counts, $name',
        'I’m glad you showed up, $name',
        'Slow is fine tonight, $name',
        'You’re not alone here, $name',
        'Ease into this, $name',
        'Night can be gentle, $name',
        'One more quiet tap, $name',
        'You’re doing alright, $name',
        'Low pressure mode, $name',
        'Soft focus only, $name',
        'This can wait till dawn, $name',
        'Come as you are, $name',
        'Late nights, soft goals, $name',
        'Steady and slow, $name',
        'A little is enough, $name',
        'Welcome back, $name',
        'Quiet courage looks good, $name',
        'Let’s keep this easy, $name',
      ];
    }
    if (hour < 12) {
      return [
        'Good morning, $name',
        'Morning, $name',
        'Hey $name — nice start',
        'Fresh day, $name',
        'Hope you slept well, $name',
        'Ready when you are, $name',
        'Let’s ease into today, $name',
        'You’ve got this, $name',
        'Bright morning, $name',
        'Start soft, $name',
        'Glad to see you, $name',
        'Make today yours, $name',
        'One habit at a time, $name',
        'Clear head, open day, $name',
        'Morning looks good on you, $name',
        'Begin kindly, $name',
        'Small wins first, $name',
        'Coffee and calm, $name',
        'Today can be gentle, $name',
        'Nice to have you here, $name',
        'Steady start, $name',
        'Take the morning slow, $name',
        'You’re right on time, $name',
        'Hello again, $name',
        'A quiet good morning, $name',
        'Let’s build something small, $name',
        'New day, same you — strong, $name',
        'Light steps today, $name',
        'Begin with what matters, $name',
        'You’ve got room to breathe, $name',
        'Morning energy, softly, $name',
        'Welcome to today, $name',
      ];
    }
    if (hour < 17) {
      return [
        'Hey $name',
        'Good afternoon, $name',
        'Back again, $name',
        'Keep going — you’re doing well, $name',
        'Nice to see you, $name',
        'Still showing up. That matters, $name',
        'How’s the day treating you, $name?',
        'Steady as you go, $name',
        'You’ve got this stretch, $name',
        'Midday reset, $name',
        'One check-in at a time, $name',
        'Pace yourself, $name',
        'You’re in a good rhythm, $name',
        'Progress over perfect, $name',
        'Come take a breath, $name',
        'Glad you returned, $name',
        'Keep it calm this afternoon, $name',
        'Solid work so far, $name',
        'Stay with what’s next, $name',
        'You’re doing better than you think, $name',
        'Make a little space, $name',
        'Afternoon looks open for you, $name',
        'Tap in when you’re ready, $name',
        'Quiet momentum suits you, $name',
        'Here whenever you need a reset, $name',
        'Second wind incoming, $name',
        'Keep the afternoon kind, $name',
        'You’re right where you need to be, $name',
        'Small steps still count, $name',
        'Nice pace today, $name',
        'Let’s keep this simple, $name',
        'Welcome back, $name',
      ];
    }
    if (hour < 21) {
      return [
        'Good evening, $name',
        'Evening, $name',
        'Hey $name — winding down?',
        'You showed up today, $name',
        'Nice work today, $name',
        'Ease into the evening, $name',
        'You did enough, $name',
        'Soft landing tonight, $name',
        'Proud of how you showed up, $name',
        'Let the day settle, $name',
        'Golden hour check-in, $name',
        'Close the day kindly, $name',
        'Thank yourself for today, $name',
        'Evening looks peaceful, $name',
        'Unclench a little, $name',
        'Good enough is good, $name',
        'Wrap up gently, $name',
        'You’ve earned a slower pace, $name',
        'Come rest a moment, $name',
        'The hard part’s behind you, $name',
        'Quiet evening, $name',
        'Be gentle with yourself now, $name',
        'One last soft check-in, $name',
        'Day’s nearly done — well done, $name',
        'Settle in, $name',
        'You carried a lot today, $name',
        'Evening reset for you, $name',
        'Lighten the load a bit, $name',
        'Still glad you’re here, $name',
        'Make tonight easy, $name',
        'Rest is part of the work, $name',
        'Close with care, $name',
      ];
    }
    return [
      'Late night, $name?',
      'Almost bedtime, $name',
      'Take it easy now, $name',
      'You made it through today, $name',
      'Quiet wins tonight, $name',
      'Rest soon, $name',
      'No pressure this late, $name',
      'One gentle check-in, $name',
      'You’re still here — that’s enough, $name',
      'Keep tonight soft, $name',
      'Dim the noise, $name',
      'Almost there, $name',
      'Be kind before sleep, $name',
      'Late nights call for ease, $name',
      'Small finish, big care, $name',
      'You’ve done plenty, $name',
      'Let tomorrow wait, $name',
      'Soft landing ahead, $name',
      'Glad you checked in, $name',
      'Night can be gentle, $name',
      'Low stakes only, $name',
      'Come as you are, $name',
      'Close the day kindly, $name',
      'Sleep will sort the rest, $name',
      'Easy does it, $name',
      'A quiet goodnight almost, $name',
      'You’re okay to slow down, $name',
      'Finish light, $name',
      'Protect your rest, $name',
      'Tonight, less is more, $name',
      'Still proud of you, $name',
      'Wind down with me, $name',
    ];
  }

  static List<String> _anonymous(int hour) {
    if (hour < 5) {
      return const [
        'Still awake?',
        'Late night check-in',
        'Take it easy',
        'Quiet hours',
        'Glad you’re here',
        'No rush tonight',
        'One gentle step',
        'Rest when you can',
        'You’ve done enough',
        'Soft night ahead',
        'Keep it light',
        'Breathe — you’re okay',
        'Almost morning',
        'Be kind to yourself',
        'Small progress counts',
        'Slow is fine tonight',
        'Ease into this',
        'Night can be gentle',
        'One more quiet tap',
        'You’re doing alright',
        'Low pressure mode',
        'Soft focus only',
        'Come as you are',
        'Steady and slow',
        'A little is enough',
        'Welcome back',
        'Let’s keep this easy',
        'Quiet courage',
        'Still showing up',
        'Gentle pace',
        'Night reset',
        'Soft ambition only',
      ];
    }
    if (hour < 12) {
      return const [
        'Good morning',
        'Morning',
        'Fresh day',
        'Hope you slept well',
        'Ready when you are',
        'Let’s ease into today',
        'You’ve got this',
        'Bright morning',
        'Start soft',
        'Glad to see you',
        'Make today yours',
        'One habit at a time',
        'Clear head, open day',
        'Begin kindly',
        'Small wins first',
        'Coffee and calm',
        'Today can be gentle',
        'Nice to have you here',
        'Steady start',
        'Take the morning slow',
        'You’re right on time',
        'Hello again',
        'A quiet good morning',
        'Light steps today',
        'Begin with what matters',
        'You’ve got room to breathe',
        'Welcome to today',
        'Soft morning energy',
        'New page',
        'Rise gently',
        'Start where you are',
        'Morning looks open',
      ];
    }
    if (hour < 17) {
      return const [
        'Good afternoon',
        'Hey you',
        'Back again',
        'Keep going — you’re doing well',
        'Nice to see you',
        'Still showing up. That matters',
        'How’s the day treating you?',
        'Steady as you go',
        'Midday reset',
        'One check-in at a time',
        'Pace yourself',
        'You’re in a good rhythm',
        'Progress over perfect',
        'Come take a breath',
        'Glad you returned',
        'Keep it calm this afternoon',
        'Solid work so far',
        'Stay with what’s next',
        'You’re doing better than you think',
        'Make a little space',
        'Afternoon looks open',
        'Tap in when you’re ready',
        'Quiet momentum',
        'Here for a reset',
        'Second wind incoming',
        'Keep the afternoon kind',
        'You’re right where you need to be',
        'Small steps still count',
        'Nice pace today',
        'Let’s keep this simple',
        'Welcome back',
        'Soft focus afternoon',
      ];
    }
    if (hour < 21) {
      return const [
        'Good evening',
        'Evening',
        'Winding down?',
        'You showed up today',
        'Nice work today',
        'Ease into the evening',
        'You did enough',
        'Soft landing tonight',
        'Proud of how you showed up',
        'Let the day settle',
        'Golden hour check-in',
        'Close the day kindly',
        'Thank yourself for today',
        'Evening looks peaceful',
        'Unclench a little',
        'Good enough is good',
        'Wrap up gently',
        'You’ve earned a slower pace',
        'Come rest a moment',
        'The hard part’s behind you',
        'Quiet evening',
        'Be gentle with yourself now',
        'One last soft check-in',
        'Day’s nearly done — well done',
        'Settle in',
        'You carried a lot today',
        'Evening reset',
        'Lighten the load a bit',
        'Still glad you’re here',
        'Make tonight easy',
        'Rest is part of the work',
        'Close with care',
      ];
    }
    return const [
      'Late night?',
      'Almost bedtime',
      'Take it easy now',
      'You made it through today',
      'Quiet wins tonight',
      'Rest soon',
      'No pressure this late',
      'One gentle check-in',
      'You’re still here — that’s enough',
      'Keep tonight soft',
      'Dim the noise',
      'Almost there',
      'Be kind before sleep',
      'Late nights call for ease',
      'Small finish, big care',
      'You’ve done plenty',
      'Let tomorrow wait',
      'Soft landing ahead',
      'Glad you checked in',
      'Night can be gentle',
      'Low stakes only',
      'Come as you are',
      'Close the day kindly',
      'Sleep will sort the rest',
      'Easy does it',
      'A quiet goodnight almost',
      'You’re okay to slow down',
      'Finish light',
      'Protect your rest',
      'Tonight, less is more',
      'Still proud of you',
      'Wind down with me',
    ];
  }
}
