import 'dart:math';

abstract final class PulseGreetings {
  static String? _last;

  /// Short greetings (about one line). Avoids repeating the last one.
  static String forUser(String rawName) {
    final name = rawName.trim();
    final hour = DateTime.now().hour;
    final pool = name.isEmpty
        ? _anonymous(hour)
        : _named(hour, _firstName(name));

    if (pool.length == 1) {
      _last = pool.first;
      return pool.first;
    }

    String next;
    do {
      next = pool[Random().nextInt(pool.length)];
    } while (next == _last && pool.length > 1);
    _last = next;
    return next;
  }

  static String _firstName(String name) {
    final parts = name.split(RegExp(r'\s+'));
    final first = parts.first;
    if (first.isEmpty) return name;
    return first[0].toUpperCase() + first.substring(1);
  }

  static List<String> _named(int hour, String name) {
    // Time-aware openers + shared calm lines. Each daypart pool is 30+.
    if (hour < 5) {
      return [
        'Still up, $name?',
        'Night owl, $name',
        'Quiet hours, $name',
        'Soft night, $name',
        'Late pulse, $name',
        'Easy does it, $name',
        'Moonlight mode, $name',
        'Gentle pace, $name',
        'One quiet tap, $name',
        'Slow and steady, $name',
        'Keep it light, $name',
        'Night notes, $name',
        'Rest is progress, $name',
        'Whisper mode, $name',
        'Low lights, $name',
        'Quiet wins, $name',
        'Almost dawn, $name',
        'Hush and focus, $name',
        'Tiny steps, $name',
        'You’re here, $name',
        'Calm carry-on, $name',
        'No rush, $name',
        'Soft landing, $name',
        'Late legend, $name',
        'Pulse after dark, $name',
        'Kind to yourself, $name',
        'One more breath, $name',
        'Still glowing, $name',
        'Night garden, $name',
        'Peaceful tap, $name',
        'Dim and determined, $name',
        'Quiet courage, $name',
      ];
    }
    if (hour < 12) {
      return [
        'Morning, $name',
        'Rise and pulse, $name',
        'Hey $name',
        'Let’s go, $name',
        'Fresh start, $name',
        'Coffee first, $name',
        'Good light, $name',
        'New page, $name',
        'Bright and easy, $name',
        'Start soft, $name',
        'Day begins, $name',
        'Ready when you are, $name',
        'Clear morning, $name',
        'Small wins ahead, $name',
        'Open gently, $name',
        'Sunrise energy, $name',
        'Make it count, $name',
        'Warm hello, $name',
        'First rhythm, $name',
        'You’ve got time, $name',
        'Steady morning, $name',
        'Begin kindly, $name',
        'Light steps, $name',
        'Morning pulse, $name',
        'Nice to see you, $name',
        'Today’s yours, $name',
        'Simple start, $name',
        'Wake and win, $name',
        'Fresh air energy, $name',
        'Quiet ambition, $name',
        'Hello again, $name',
        'Plant the day, $name',
      ];
    }
    if (hour < 17) {
      return [
        'Hey $name',
        'Back at it, $name',
        'Afternoon, $name',
        'Keep going, $name',
        'You got this, $name',
        'Midday pulse, $name',
        'Still steady, $name',
        'Nice pace, $name',
        'Carry on, $name',
        'In the flow, $name',
        'Right on time, $name',
        'Build quietly, $name',
        'One more check-in, $name',
        'Solid stretch, $name',
        'Stay with it, $name',
        'Afternoon light, $name',
        'You’re showing up, $name',
        'Keep it calm, $name',
        'Momentum looks good, $name',
        'Midday kindness, $name',
        'Progress over perfect, $name',
        'Tap and breathe, $name',
        'Here we are, $name',
        'Quiet grit, $name',
        'Good rhythm, $name',
        'Second wind, $name',
        'Soft focus, $name',
        'You’ve got room, $name',
        'Stay curious, $name',
        'Afternoon glow, $name',
        'Make space, $name',
        'Keep the pulse, $name',
      ];
    }
    if (hour < 21) {
      return [
        'Evening, $name',
        'Soft landings, $name',
        'Nice work, $name',
        'Wind down, $name',
        'Hey $name',
        'Golden hour, $name',
        'Ease in, $name',
        'Evening pulse, $name',
        'Gentle close, $name',
        'You showed up, $name',
        'Quiet pride, $name',
        'Unclench a little, $name',
        'Soft finish, $name',
        'Day’s almost done, $name',
        'Warm light, $name',
        'Settle kindly, $name',
        'One last rhythm, $name',
        'Evening calm, $name',
        'Good enough is good, $name',
        'Close with care, $name',
        'Low volume wins, $name',
        'Thank yourself, $name',
        'Dusk and done, $name',
        'Ease the edges, $name',
        'Still proud of you, $name',
        'Lighten up, $name',
        'Evening garden, $name',
        'Soft applause, $name',
        'Rest is coming, $name',
        'Quiet wins, $name',
        'Wrap it gently, $name',
        'You did enough, $name',
      ];
    }
    return [
      'Late legend, $name',
      'One more, $name?',
      'Quiet wins, $name',
      'Night pulse, $name',
      'Soft night, $name',
      'Dim the noise, $name',
      'Almost there, $name',
      'Late and lovely, $name',
      'Hush mode, $name',
      'Tiny victory, $name',
      'Night notes, $name',
      'Keep it gentle, $name',
      'Last light, $name',
      'Calm close, $name',
      'You’re still here, $name',
      'Quiet courage, $name',
      'Soft tap, $name',
      'Night garden, $name',
      'Low and steady, $name',
      'Rest soon, $name',
      'One quiet check-in, $name',
      'Moonlit progress, $name',
      'No pressure, $name',
      'Late bloom, $name',
      'Whisper wins, $name',
      'Easy night, $name',
      'Finish kind, $name',
      'Pulse before bed, $name',
      'Gentle grit, $name',
      'Still glowing, $name',
      'Close the loop, $name',
      'Sleep is next, $name',
    ];
  }

  static List<String> _anonymous(int hour) {
    if (hour < 5) {
      return const [
        'Quiet hours',
        'Night owl mode',
        'Soft night',
        'Easy does it',
        'Low lights',
        'Gentle pace',
        'Still here',
        'Hush and focus',
        'Tiny steps',
        'Night pulse',
        'Calm carry-on',
        'No rush',
        'Quiet wins',
        'Soft landing',
        'One more breath',
        'Moonlight mode',
        'Rest is progress',
        'Whisper mode',
        'Almost dawn',
        'Peaceful tap',
        'Slow and steady',
        'Kind to yourself',
        'Late legend',
        'Dim and determined',
        'Quiet courage',
        'Night garden',
        'Still glowing',
        'One quiet tap',
        'Night notes',
        'Keep it light',
        'Soft focus',
        'Pulse after dark',
      ];
    }
    if (hour < 12) {
      return const [
        'Good morning',
        'Hey early bird',
        'Fresh start',
        'Rise and pulse',
        'Coffee first',
        'New page',
        'Bright and easy',
        'Start soft',
        'Clear morning',
        'Small wins ahead',
        'Open gently',
        'Sunrise energy',
        'Warm hello',
        'First rhythm',
        'Steady morning',
        'Begin kindly',
        'Light steps',
        'Morning pulse',
        'Today’s yours',
        'Simple start',
        'Wake and win',
        'Quiet ambition',
        'Hello again',
        'Plant the day',
        'Good light',
        'Ready when you are',
        'Make it count',
        'You’ve got time',
        'Fresh air energy',
        'Day begins',
        'Nice to see you',
        'Soft morning',
      ];
    }
    if (hour < 17) {
      return const [
        'Good afternoon',
        'Hey you',
        'Back at it',
        'Keep going',
        'You got this',
        'Midday pulse',
        'Still steady',
        'Nice pace',
        'Carry on',
        'In the flow',
        'Build quietly',
        'Stay with it',
        'Afternoon light',
        'Keep it calm',
        'Progress over perfect',
        'Tap and breathe',
        'Quiet grit',
        'Good rhythm',
        'Second wind',
        'Soft focus',
        'Stay curious',
        'Afternoon glow',
        'Make space',
        'Keep the pulse',
        'Solid stretch',
        'Right on time',
        'You’re showing up',
        'Midday kindness',
        'Here we are',
        'Momentum looks good',
        'One more check-in',
        'Soft ambition',
      ];
    }
    if (hour < 21) {
      return const [
        'Good evening',
        'Soft landings',
        'Wind down',
        'Golden hour',
        'Ease in',
        'Evening pulse',
        'Gentle close',
        'You showed up',
        'Quiet pride',
        'Soft finish',
        'Warm light',
        'Settle kindly',
        'Evening calm',
        'Close with care',
        'Low volume wins',
        'Thank yourself',
        'Ease the edges',
        'Lighten up',
        'Evening garden',
        'Soft applause',
        'Quiet wins',
        'Wrap it gently',
        'You did enough',
        'Nice work',
        'Unclench a little',
        'Day’s almost done',
        'One last rhythm',
        'Good enough is good',
        'Dusk and done',
        'Rest is coming',
        'Still proud',
        'Soft evening',
      ];
    }
    return const [
      'Night rider',
      'Soft landings',
      'Quiet wins',
      'Night pulse',
      'Late legend',
      'One more?',
      'Dim the noise',
      'Hush mode',
      'Tiny victory',
      'Night notes',
      'Keep it gentle',
      'Calm close',
      'Quiet courage',
      'Soft tap',
      'Night garden',
      'Low and steady',
      'Rest soon',
      'Moonlit progress',
      'No pressure',
      'Late bloom',
      'Whisper wins',
      'Easy night',
      'Finish kind',
      'Gentle grit',
      'Still glowing',
      'Close the loop',
      'Sleep is next',
      'Almost there',
      'Soft night',
      'Pulse before bed',
      'One quiet check-in',
      'Late and lovely',
    ];
  }
}
